source('3_visualize/src/drought_learner_viz_components.R')

p3_targets <- list(
       
  #### Creates a series of ggplot pngs that will get pulled together downstream
  #
  # NOTE: Must make sure that target 'p2_1951_2020_metadata_subset' includes the correct data
  #
  tar_target(p3_blank_plot,
             blank_plot(p2_streamflow_learner_viz_df)),
  tar_target(p3_inset_map,
             inset_map()),
  tar_target(p3_canvas,
             background_canvas()),
  tar_target(p3_bottom_bars_fixed,
             bottom_bars(both = F, p2_droughts_learner_viz_df, blank_plot = p3_blank_plot)),
  tar_target(p3_bottom_bars_both,
             bottom_bars(both = T, p2_droughts_learner_viz_df, blank_plot = p3_blank_plot)),
  
  tar_target(p3_drought_learner_viz_a_png,
             frame_a(p3_blank_plot,
                     p2_streamflow_learner_viz_df,
                     droughts = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/a.png"),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_b_png,
             frame_b(p3_blank_plot,
                     p2_streamflow_learner_viz_df,
                     p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/b.png"),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_c_png,
             frame_c(p3_blank_plot,
                     p2_streamflow_learner_viz_df,
                     p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/c.png"),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_d_png,
             frame_d(p3_blank_plot,
                     p2_streamflow_learner_viz_df,
                     p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/d.png"),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_e_png,
             frame_e(p3_blank_plot,
                     p2_streamflow_learner_viz_df,
                     p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/e.png"),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_f_png,
             frame_f(p3_blank_plot,
                     p2_streamflow_learner_viz_df,
                     p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/f.png"),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_g_png,
             frame_g(p3_blank_plot,
                     p2_streamflow_learner_viz_df,
                     p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/g.png"),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_h_png,
             frame_h(p3_blank_plot,
                     p2_streamflow_learner_viz_df,
                     p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/h.png"),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_i_png,
             frame_i(p3_blank_plot,
                     p2_streamflow_learner_viz_df,
                     p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/i.png"),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_j_png,
             frame_j(p3_blank_plot,
                     p2_streamflow_learner_viz_df,
                     p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_both,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/j.png"),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_k_png,
             frame_k(p3_blank_plot,
                     p2_streamflow_learner_viz_df,
                     p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_both,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/k.png"),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_l_png,
             frame_l(p2_streamflow_learner_viz_df,
                     p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_both,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/l.png"),
             format = "file")
)

