source('3_visualize/src/drought_learner_viz_components.R')

p3_targets <- list(
       
  
  # Global design variables to be used in each frame, with "dv_" as prefix for "design variable"
  tar_target(p3_dv_tibble,
             tibble(
               # Drought events
               dv_drought_fill_variable = "#e6af84",
               dv_drought_fill_fixed = "#da7d81",
               dv_drought_threshold_variable = "#a44a23",
               dv_drought_threshold_fixed = "#c1272d",
               dv_drought_textColor = "#c1272d",
               # Streamflow
               dv_streamflow_line_daily = "#1e41b5",
               dv_streamflow_line_annual_average = "#da7d81",
               dv_streamflow_line_daily_average = "#c3e8fa",
               dv_streamflow_textcolor_daily = "#1e41b5",
               dv_streamflow_textcolor_annual_average = "#da7d81",
               dv_streamflow_textcolor_daily_average = "#5691e2",
               # Other Annotations
               dv_circle_explainer = "#a44a23",
             )
  ),
  
  
  
  #### Creates a series of ggplot pngs that will get pulled together downstream
  #
  # NOTE: Must make sure that target 'p2_1951_2020_metadata_subset' includes the correct data
  #
  tar_target(p3_blank_plot,
             blank_plot(streamflow_df = p2_streamflow_learner_viz_df)),
  tar_target(p3_inset_map,
             inset_map()),
  tar_target(p3_canvas,
             background_canvas()),
  tar_target(p3_bottom_bars_fixed,
             bottom_bars(both = F, 
                         droughts_df = p2_droughts_learner_viz_df, 
                         blank_plot = p3_blank_plot,
                         dv_tibble = p3_dv_tibble)),
  tar_target(p3_bottom_bars_both,
             bottom_bars(both = T, 
                         droughts_df = p2_droughts_learner_viz_df, 
                         blank_plot = p3_blank_plot,
                         dv_tibble = p3_dv_tibble)),
  
  tar_target(p3_drought_learner_viz_a_png,
             frame_a(p3_blank_plot,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/a.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_b_png,
             frame_b(p3_blank_plot,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/b.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_c_png,
             frame_c(p3_blank_plot,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/c.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_d_png,
             frame_d(p3_blank_plot,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/d.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_e_png,
             frame_e(p3_blank_plot,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/e.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_f_png,
             frame_f(p3_blank_plot,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/f.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_g_png,
             frame_g(p3_blank_plot,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/g.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_h_png,
             frame_h(p3_blank_plot,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/h.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_i_png,
             frame_i(p3_blank_plot,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/i.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_j_png,
             frame_j(p3_blank_plot,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_both,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/j.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_k_png,
             frame_k(p3_blank_plot,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_both,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/k.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_l_png,
             frame_l(streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_both,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/l.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_m_png,
             frame_m(streamflow_df = p2_streamflow_learner_viz_df, 
                     droughts_df = p2_droughts_learner_viz_df,
                     droughts_70yr_site_df = p2_droughts_70year_stacked_site_df, 
                     droughts_70yr_j7_df = p2_droughts_70year_stacked_j7_df, 
                     canvas = p3_canvas, 
                     out_png = "src/assets/images/threshold-chart/m.png",
                     dv_tibble = p3_dv_tibble),
             format = "file")
)

