source('3_visualize/src/drought_learner_viz_components.R')

p3_targets <- list(
       
  
  # Global design variables to be used in each frame, with "dv_" as prefix for "design variable"
  tar_target(p3_dv_tibble,
             tibble(
               # Drought events
               dv_drought_fill_variable = "#FCC065",
               dv_drought_fill_fixed = "#E76254",
               dv_drought_threshold_variable = "#F7931E",
               dv_drought_threshold_fixed = "#A00E00",
               dv_drought_textColor = "#E76254",
               dv_threshold_line_size = 0.5, #default = 0.5
               # Streamflow
               dv_streamflow_line_daily = "#3F729C",
               dv_streamflow_line_annual_average = "#FFE3AD",
               dv_streamflow_line_daily_average = "#a2d7de",
               dv_streamflow_textcolor_daily = "#3F729C",
               dv_streamflow_textcolor_annual_average = "#FCC065",
               dv_streamflow_textcolor_daily_average = "#64A8C4",
               dv_streamflow_line_size = 0.3, #default = 0.5
               # Other Annotations
               dv_circle_explainer = "#E76254",
               dv_shading_fill = "white",
               dv_zoom_box_outline = "black",
               dv_zoom_box_lines = "black",
               dv_axis_additions_stackedYear = "#666666",
               # png sizing,
               dv_png_width = 1200, 
               dv_png_height = 800,
               # Base plot design
               dv_basePlot_axis_color = "#132B69",
               dv_basePlot_axis_size = 0.1,
               dv_basePlot_axis_text_color = "#132B69"
             )
  ),
  
  
  
  #### Creates a series of ggplot pngs that will get pulled together downstream
  #
  # NOTE: Must make sure that target 'p2_1951_2020_metadata_subset' includes the correct data
  #

    # This is for most frames, focused on growing season
  tar_target(p3_blank_plot_summer,
             blank_plot(streamflow_df = p2_streamflow_learner_viz_df,
                        dv_tibble = p3_dv_tibble,
                        growing_season = T)),
    # This is for the frames showing a whole year
  tar_target(p3_blank_plot_year,
             blank_plot(streamflow_df = p2_streamflow_learner_viz_df,
                        dv_tibble = p3_dv_tibble,
                        growing_season = F)),
  
  tar_target(p3_inset_map,
             inset_map(state_fill = "#ffe3ad",
                       border_size = 0.1,
                       border_fill = "#ffeece",
                       highlight_site_color = "#A00E00")),
  tar_target(p3_canvas,
             background_canvas()),
  tar_target(p3_bottom_bars_fixed,
             bottom_bars(both = F, 
                         droughts_df = p2_droughts_learner_viz_df, 
                         blank_plot = p3_blank_plot_summer,
                         dv_tibble = p3_dv_tibble)),
  tar_target(p3_bottom_bars_both,
             bottom_bars(both = T, 
                         droughts_df = p2_droughts_learner_viz_df, 
                         blank_plot = p3_blank_plot_summer,
                         dv_tibble = p3_dv_tibble)),
  
  tar_target(p3_drought_learner_viz_a_png,
             frame_a(blank_plot = p3_blank_plot_summer,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/a.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_b_png,
             frame_b(blank_plot = p3_blank_plot_summer,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/b.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_c_png,
             frame_c(blank_plot = p3_blank_plot_summer,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/c.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_d_png,
             frame_d(blank_plot = p3_blank_plot_summer,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/d.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_e_png,
             frame_e(blank_plot = p3_blank_plot_summer,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/e.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_f_png,
             frame_f(blank_plot = p3_blank_plot_summer,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/f.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_g_png,
             frame_g(blank_plot = p3_blank_plot_summer,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/g.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_h_png,
             frame_h(blank_plot = p3_blank_plot_summer,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/h.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_i_png,
             frame_i(blank_plot = p3_blank_plot_summer,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_fixed,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/i.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_j_png,
             frame_j(blank_plot = p3_blank_plot_summer,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_both,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/j.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_k_png,
             frame_k(blank_plot = p3_blank_plot_summer,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_both,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/k.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_l_png,
             frame_l(blank_plot = p3_blank_plot_year,
                     streamflow_df = p2_streamflow_learner_viz_df,
                     droughts_df = p2_droughts_learner_viz_df,
                     bottom_bars = p3_bottom_bars_both,
                     inset = p3_inset_map,
                     canvas = p3_canvas,
                     out_png = "src/assets/images/threshold-chart/l.png",
                     dv_tibble = p3_dv_tibble),
             format = "file"),
  
  tar_target(p3_drought_learner_viz_m_png,
             frame_m(blank_plot = p3_blank_plot_year,
                     streamflow_df = p2_streamflow_learner_viz_df, 
                     droughts_df = p2_droughts_learner_viz_df,
                     droughts_70yr_site_df = p2_droughts_70year_stacked_site_df, 
                     droughts_70yr_j7_df = p2_droughts_70year_stacked_j7_df, 
                     canvas = p3_canvas, 
                     out_png = "src/assets/images/threshold-chart/m.png",
                     dv_tibble = p3_dv_tibble),
             format = "file")
)

